### ISSUE TITLE
UI and Bot need to be run from child directories instead of parent

### ISSUE THREAD

**Issue by pawptart** [GooeyBot/Gooey#6]
With the new absolute imports from #3, the bot and UI cannot be run from the parent `gooey` directory. Instead, you must change directory into the respective child and run the applications there.

Essentially, this still makes the app two separate projects. Moving forward, proper namespacing should be considered in order to make this function as a whole:

```
python gooey/gooey.py
Traceback (most recent call last):
  File "gooey/gooey.py", line 56, in <module>
    Gooey().start()
  File "gooey/gooey.py", line 28, in __init__
    self.handler = self.select_handler()
  File "gooey/gooey.py", line 35, in select_handler
    module = importlib.import_module(handler)
  File "/home/portertb/.asdf/installs/python/3.8.0/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/portertb/dev/gooey/gooey/handlers/economy.py", line 1, in <module>
    from gooey.handlers.errors import FunctionNotAllowed, CommandNotMatched
ModuleNotFoundError: No module named 'gooey.handlers'; 'gooey' is not a package
``` 

Running the UI from the `gooey` directory loads the app correctly but then fails on navigation.

**Comment by pawptart** [comment]
Currently investigating the value of fixing this since it might be easier to treat this as two separate projects linked by a single configuration file.
